# Auto-generated by claude-use's release workflow on every tagged release — do not edit manually.
class ClaudeUse < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/claude-use"
  version "0.2.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v0.2.3/claude-use-macos-arm64"
      sha256 "de2e3aa34f52e56c542b04734d695c710ca16cd125febc3ee2b9e20554644287"
    end
    on_intel do
      url "https://github.com/ExaDev/claude-use/releases/download/v0.2.3/claude-use-macos-x64-unverified"
      sha256 "f0dbc2de76f3603f518acc2d2f36f482da37e8bb5c01c601e03fffe4c85e36ad"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v0.2.3/claude-use-linux-arm64"
      sha256 "65235bd578c240732be754268027612aaaa3399454f9a760e31f6e7339edcf53"
    end
    on_intel do
      url "https://github.com/ExaDev/claude-use/releases/download/v0.2.3/claude-use-linux-x64"
      sha256 "dc2d6d09effc1d9c0911b1f4abef93841f8f64b592ece5b505c0a2ca906c5b14"
    end
  end

  def install
    downloaded = Dir["claude-use-*"].first
    bin.install downloaded => "claude-use"
    chmod 0755, bin/"claude-use"
  end

  def caveats
    <<~EOS
      claude-use is installed alone -- nothing on this system claims the `claude` command by default.
      Run `claude-use run [args...]` to use the launcher directly, or `claude-use shim enable` once
      if you'd also like the shorter `claude @<name>` form (`claude-use shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-use --version")
  end
end
