# Auto-generated by claude-use's release workflow on every tagged release — do not edit manually.
class ClaudeUse < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/claude-use"
  version "2.4.2"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.4.2/claude-use-macos-arm64"
      sha256 "b6c7ac0fbdd41bdc78a75f1cf8a06b80a355842eec411c23939d9adcef8a9187"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see README.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/claude-use/-/claude-use-2.4.2.tgz"
      sha256 "5e9af410b37b66a012a0c8aacc6daa207e5d41f8dd7096e4337845ac19ff00fc"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.4.2/claude-use-linux-arm64"
      sha256 "ecf5adbcead3f23dda0b5100138527ebe1a4eeb9ada55207146c680806eddb55"
    end
    on_intel do
      url "https://github.com/ExaDev/claude-use/releases/download/v2.4.2/claude-use-linux-x64"
      sha256 "109c5f93ac1a2a53e1713b8eef4225a8966a88b6e759696d0322dbca7825d026"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["claude-use-*"].first
      bin.install downloaded => "claude-use"
      chmod 0755, bin/"claude-use"
    end
  end

  def caveats
    <<~EOS
      claude-use is installed alone -- nothing on this system claims the `claude` command by default.
      Run `claude-use run [args...]` to use the launcher directly, or `claude-use shim enable` once
      if you'd also like the shorter `claude @<name>` form (`claude-use shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-use --version")
  end
end
