# Auto-generated by claude-use's release workflow on every tagged release — do not edit manually.
class ClaudeUse < Formula
  desc "Profile manager and launcher for Claude Code with per-directory sharing rules"
  homepage "https://github.com/ExaDev/claude-use"
  version "0.2.10"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v0.2.10/claude-use-macos-arm64"
      sha256 "fea089ee8de5ad8196750247dc0d9b318bef0effe12ea5e0846300b0ae2b97c4"
    end
    on_intel do
      # The SEA binary segfaults on every invocation on real x64 macOS hardware -- a known, unfixed upstream Node bug (see README.md's "Build (Node SEA)" section for the full writeup and citations). Installs via npm + a Homebrew-managed Node instead, same code this project already publishes and verifies on the npm channel, on every other platform.
      url "https://registry.npmjs.org/claude-use/-/claude-use-0.2.10.tgz"
      sha256 "c1678e285181fafc5c858720f7857a254bdd7765e02b3cd3b33d6885986e26dc"
      depends_on "node"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/ExaDev/claude-use/releases/download/v0.2.10/claude-use-linux-arm64"
      sha256 "c5ba4a0d97ac720be4378ff7d6e14305a9b488779f4ea1f76d5ad93456197610"
    end
    on_intel do
      url "https://github.com/ExaDev/claude-use/releases/download/v0.2.10/claude-use-linux-x64"
      sha256 "79cbe67897fefde2b0b5b3c03d65229c70b5bc36eef8305c6dae6f8b5df7e4c7"
    end
  end

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      downloaded = Dir["claude-use-*"].first
      bin.install downloaded => "claude-use"
      chmod 0755, bin/"claude-use"
    end
  end

  def caveats
    <<~EOS
      claude-use is installed alone -- nothing on this system claims the `claude` command by default.
      Run `claude-use run [args...]` to use the launcher directly, or `claude-use shim enable` once
      if you'd also like the shorter `claude @<name>` form (`claude-use shim disable` undoes it).
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/claude-use --version")
  end
end
